# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/config_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        Form.setStyleSheet("background-color: rgb(11, 19, 43);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMaximumSize(QtCore.QSize(480, 30))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_tittle = QtWidgets.QLabel(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tittle.sizePolicy().hasHeightForWidth())
        self.lbl_tittle.setSizePolicy(sizePolicy)
        self.lbl_tittle.setMinimumSize(QtCore.QSize(200, 15))
        self.lbl_tittle.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tittle.setFont(font)
        self.lbl_tittle.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tittle.setObjectName("lbl_tittle")
        self.horizontalLayout_4.addWidget(self.lbl_tittle)
        self.verticalLayout.addWidget(self.top_bar)
        self.central_layout = QtWidgets.QHBoxLayout()
        self.central_layout.setSpacing(10)
        self.central_layout.setObjectName("central_layout")
        self.left_panel = QtWidgets.QVBoxLayout()
        self.left_panel.setObjectName("left_panel")
        self.lbl_recipes = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_recipes.sizePolicy().hasHeightForWidth())
        self.lbl_recipes.setSizePolicy(sizePolicy)
        self.lbl_recipes.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recipes.setFont(font)
        self.lbl_recipes.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_recipes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recipes.setObjectName("lbl_recipes")
        self.left_panel.addWidget(self.lbl_recipes)
        self.cmb_recipes = QtWidgets.QComboBox(Form)
        self.cmb_recipes.setMaximumSize(QtCore.QSize(200, 25))
        self.cmb_recipes.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 3px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.cmb_recipes.setObjectName("cmb_recipes")
        self.left_panel.addWidget(self.cmb_recipes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add_r = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_r.sizePolicy().hasHeightForWidth())
        self.btn_add_r.setSizePolicy(sizePolicy)
        self.btn_add_r.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_add_r.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_add_r.setObjectName("btn_add_r")
        self.horizontalLayout.addWidget(self.btn_add_r)
        self.btn_del_r = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_r.sizePolicy().hasHeightForWidth())
        self.btn_del_r.setSizePolicy(sizePolicy)
        self.btn_del_r.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_del_r.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_del_r.setObjectName("btn_del_r")
        self.horizontalLayout.addWidget(self.btn_del_r)
        self.left_panel.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_select_r = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_r.sizePolicy().hasHeightForWidth())
        self.btn_select_r.setSizePolicy(sizePolicy)
        self.btn_select_r.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_select_r.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_select_r.setObjectName("btn_select_r")
        self.horizontalLayout_5.addWidget(self.btn_select_r)
        self.left_panel.addLayout(self.horizontalLayout_5)
        self.central_layout.addLayout(self.left_panel)
        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("background-color: rgb(15, 27, 61);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.central_layout.addWidget(self.line)
        self.right_panel = QtWidgets.QVBoxLayout()
        self.right_panel.setObjectName("right_panel")
        self.lbl_tools = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tools.sizePolicy().hasHeightForWidth())
        self.lbl_tools.setSizePolicy(sizePolicy)
        self.lbl_tools.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tools.setFont(font)
        self.lbl_tools.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_tools.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tools.setObjectName("lbl_tools")
        self.right_panel.addWidget(self.lbl_tools)
        self.cmb_tools = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_tools.sizePolicy().hasHeightForWidth())
        self.cmb_tools.setSizePolicy(sizePolicy)
        self.cmb_tools.setMaximumSize(QtCore.QSize(200, 25))
        self.cmb_tools.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 3px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.cmb_tools.setObjectName("cmb_tools")
        self.right_panel.addWidget(self.cmb_tools)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_t = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_t.sizePolicy().hasHeightForWidth())
        self.btn_add_t.setSizePolicy(sizePolicy)
        self.btn_add_t.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_add_t.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_add_t.setObjectName("btn_add_t")
        self.horizontalLayout_2.addWidget(self.btn_add_t)
        self.btn_del_t = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_t.sizePolicy().hasHeightForWidth())
        self.btn_del_t.setSizePolicy(sizePolicy)
        self.btn_del_t.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_del_t.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_del_t.setObjectName("btn_del_t")
        self.horizontalLayout_2.addWidget(self.btn_del_t)
        self.right_panel.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_t = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit_t.sizePolicy().hasHeightForWidth())
        self.btn_edit_t.setSizePolicy(sizePolicy)
        self.btn_edit_t.setMaximumSize(QtCore.QSize(95, 25))
        self.btn_edit_t.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_edit_t.setObjectName("btn_edit_t")
        self.horizontalLayout_3.addWidget(self.btn_edit_t)
        self.right_panel.addLayout(self.horizontalLayout_3)
        self.central_layout.addLayout(self.right_panel)
        self.verticalLayout.addLayout(self.central_layout)
        self.bttm_layout = QtWidgets.QHBoxLayout()
        self.bttm_layout.setSpacing(10)
        self.bttm_layout.setObjectName("bttm_layout")
        spacerItem = QtWidgets.QSpacerItem(50, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bttm_layout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_save.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_save.setObjectName("btn_save")
        self.bttm_layout.addWidget(self.btn_save)
        self.btn_out = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_out.sizePolicy().hasHeightForWidth())
        self.btn_out.setSizePolicy(sizePolicy)
        self.btn_out.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_out.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_out.setObjectName("btn_out")
        self.bttm_layout.addWidget(self.btn_out)
        spacerItem1 = QtWidgets.QSpacerItem(50, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bttm_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.bttm_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_tittle.setText(_translate("Form", "SISTEMA DE VISIÓN - CONFIGURACIÓN"))
        self.lbl_recipes.setText(_translate("Form", "RECETAS"))
        self.btn_add_r.setText(_translate("Form", "AGREGAR"))
        self.btn_del_r.setText(_translate("Form", "ELIMINAR"))
        self.btn_select_r.setText(_translate("Form", "SELECCIONAR"))
        self.lbl_tools.setText(_translate("Form", "HERRAMIENTAS"))
        self.btn_add_t.setText(_translate("Form", "AGREGAR"))
        self.btn_del_t.setText(_translate("Form", "ELIMINAR"))
        self.btn_edit_t.setText(_translate("Form", "EDITAR"))
        self.btn_save.setText(_translate("Form", "GUARDAR"))
        self.btn_out.setText(_translate("Form", "SALIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
