# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(0, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        MainWindow.setStyleSheet("background-color: rgb(11, 19, 43);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(480, 320))
        self.centralwidget.setMaximumSize(QtCore.QSize(480, 320))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(9, 5, 9, 15)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(480, 30))
        self.top_bar.setMaximumSize(QtCore.QSize(480, 30))
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_5.setContentsMargins(50, 3, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_tittle = QtWidgets.QLabel(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tittle.sizePolicy().hasHeightForWidth())
        self.lbl_tittle.setSizePolicy(sizePolicy)
        self.lbl_tittle.setMinimumSize(QtCore.QSize(200, 15))
        self.lbl_tittle.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tittle.setFont(font)
        self.lbl_tittle.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tittle.setObjectName("lbl_tittle")
        self.horizontalLayout_5.addWidget(self.lbl_tittle)
        self.btn_minimizar = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimizar.sizePolicy().hasHeightForWidth())
        self.btn_minimizar.setSizePolicy(sizePolicy)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_minimizar.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_minimizar.setStyleSheet("background-color: rgb(58, 80, 107);\n"
"border: none;\n"
"color: #EAEAEA;\n"
"font-size: 16px;\n"
"padding: 5px 10px;\n"
"background-color: rgb(28, 37, 65);")
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout_5.addWidget(self.btn_minimizar)
        self.btn_cerrar = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cerrar.sizePolicy().hasHeightForWidth())
        self.btn_cerrar.setSizePolicy(sizePolicy)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_cerrar.setStyleSheet("border: none;\n"
"color: #EAEAEA;\n"
"background-color: rgb(28, 37, 65);\n"
"background-color: rgb(255, 77, 79);")
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_5.addWidget(self.btn_cerrar)
        self.verticalLayout_3.addWidget(self.top_bar)
        self.central_panel = QtWidgets.QHBoxLayout()
        self.central_panel.setObjectName("central_panel")
        self.left_panel = QtWidgets.QVBoxLayout()
        self.left_panel.setContentsMargins(5, 0, 5, 10)
        self.left_panel.setSpacing(10)
        self.left_panel.setObjectName("left_panel")
        self.lbl_cam = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cam.setMinimumSize(QtCore.QSize(200, 20))
        self.lbl_cam.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_cam.setFont(font)
        self.lbl_cam.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_cam.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cam.setObjectName("lbl_cam")
        self.left_panel.addWidget(self.lbl_cam)
        self.video_layaout = QtWidgets.QHBoxLayout()
        self.video_layaout.setObjectName("video_layaout")
        self.lbl_video = VideoWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_video.sizePolicy().hasHeightForWidth())
        self.lbl_video.setSizePolicy(sizePolicy)
        self.lbl_video.setMinimumSize(QtCore.QSize(180, 160))
        self.lbl_video.setMaximumSize(QtCore.QSize(235, 180))
        self.lbl_video.setSizeIncrement(QtCore.QSize(0, 0))
        self.lbl_video.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 15px;\n"
"border: 2px solid;\n"
"background-color: rgb(15, 27, 61);\n"
"border-color: rgb(94, 192, 190);\n"
"")
        self.lbl_video.setText("")
        self.lbl_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video.setObjectName("lbl_video")
        self.video_layaout.addWidget(self.lbl_video)
        self.left_panel.addLayout(self.video_layaout)
        self.central_panel.addLayout(self.left_panel)
        self.right_panel = QtWidgets.QVBoxLayout()
        self.right_panel.setContentsMargins(15, 5, 5, 5)
        self.right_panel.setSpacing(5)
        self.right_panel.setObjectName("right_panel")
        spacerItem = QtWidgets.QSpacerItem(100, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.right_panel.addItem(spacerItem)
        self.lbl_model = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_model.sizePolicy().hasHeightForWidth())
        self.lbl_model.setSizePolicy(sizePolicy)
        self.lbl_model.setMinimumSize(QtCore.QSize(180, 30))
        self.lbl_model.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_model.setFont(font)
        self.lbl_model.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.lbl_model.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.right_panel.addWidget(self.lbl_model)
        self.btn_config = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config.sizePolicy().hasHeightForWidth())
        self.btn_config.setSizePolicy(sizePolicy)
        self.btn_config.setMinimumSize(QtCore.QSize(180, 30))
        self.btn_config.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_config.setFont(font)
        self.btn_config.setStyleSheet("color: rgb(234, 234, 234);\n"
"border-radius: 10px;\n"
"border: 2px solid;\n"
"border-color: rgb(91, 192, 190);\n"
"background-color: rgb(15, 27, 61);")
        self.btn_config.setObjectName("btn_config")
        self.right_panel.addWidget(self.btn_config)
        self.status_1 = QtWidgets.QHBoxLayout()
        self.status_1.setContentsMargins(0, -1, -1, -1)
        self.status_1.setSpacing(5)
        self.status_1.setObjectName("status_1")
        self.indicator_1 = QtWidgets.QPushButton(self.centralwidget)
        self.indicator_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicator_1.sizePolicy().hasHeightForWidth())
        self.indicator_1.setSizePolicy(sizePolicy)
        self.indicator_1.setMinimumSize(QtCore.QSize(35, 35))
        self.indicator_1.setMaximumSize(QtCore.QSize(35, 35))
        self.indicator_1.setStyleSheet("border: 2px solid;\n"
"font-size: 16px;\n"
"border-radius: 17px;\n"
"border-color: rgb(46, 196, 182);\n"
"color: rgb(46, 196, 182);\n"
"background-color: rgb(15, 27, 61);")
        self.indicator_1.setObjectName("indicator_1")
        self.status_1.addWidget(self.indicator_1)
        self.lbl_indicator_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_indicator_1.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_indicator_1.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_indicator_1.setFont(font)
        self.lbl_indicator_1.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: transparent;")
        self.lbl_indicator_1.setObjectName("lbl_indicator_1")
        self.status_1.addWidget(self.lbl_indicator_1)
        self.right_panel.addLayout(self.status_1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.right_panel.addItem(spacerItem1)
        self.central_panel.addLayout(self.right_panel)
        self.verticalLayout_3.addLayout(self.central_panel)
        self.bttm_bar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttm_bar.sizePolicy().hasHeightForWidth())
        self.bttm_bar.setSizePolicy(sizePolicy)
        self.bttm_bar.setMinimumSize(QtCore.QSize(460, 30))
        self.bttm_bar.setMaximumSize(QtCore.QSize(470, 30))
        self.bttm_bar.setStyleSheet("background-color: rgb(28, 37, 65);\n"
"border-radius: 10px;")
        self.bttm_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bttm_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bttm_bar.setObjectName("bttm_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bttm_bar)
        self.horizontalLayout_3.setContentsMargins(9, 6, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list_log = QtWidgets.QListWidget(self.bttm_bar)
        self.list_log.setMinimumSize(QtCore.QSize(440, 19))
        self.list_log.setMaximumSize(QtCore.QSize(445, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.list_log.setFont(font)
        self.list_log.setObjectName("list_log")
        self.horizontalLayout_3.addWidget(self.list_log)
        self.verticalLayout_3.addWidget(self.bttm_bar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_tittle.setText(_translate("MainWindow", "SISTEMA DE VISIÓN - WORKSURFACE"))
        self.btn_minimizar.setText(_translate("MainWindow", "-"))
        self.btn_cerrar.setText(_translate("MainWindow", "X"))
        self.lbl_cam.setText(_translate("MainWindow", "CAMARA"))
        self.lbl_model.setText(_translate("MainWindow", "MODELO A"))
        self.btn_config.setText(_translate("MainWindow", "CONFIGURACIÓN"))
        self.indicator_1.setText(_translate("MainWindow", "✔"))
        self.lbl_indicator_1.setText(_translate("MainWindow", "INSPECCIÓN OK/NG"))
from ui.widgets.video_widget import VideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
